# Generated by Django 5.0.4 on 2024-04-10 10:38

from django.db import migrations


# def create_group(apps, schema_editor):
#     group = apps.get_model('auth', 'Group')
#     permission = apps.get_model('auth', 'Permission')
#     db_alias = schema_editor.connection.alias
#     new_group, created = group.objects.using(db_alias).get_or_create(name='MyUsersGroup')
#     permissions = permission.objects.using(db_alias).filter(codename__in=['view_somemodel', 'add_somemodel'])
#     new_group.permissions.add(*permissions)

def create_group(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    group.objects.get_or_create(name='all_users')


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.RunPython(create_group),
    ]
