# Generated by Django 5.0.6 on 2024-06-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communicationmethod",
            options={
                "verbose_name": "Методы связи",
                "verbose_name_plural": "Методы связи",
            },
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"verbose_name": "Материал", "verbose_name_plural": "Материалы"},
        ),
        migrations.AlterModelOptions(
            name="style",
            options={"verbose_name": "Стиль", "verbose_name_plural": "Стили"},
        ),
        migrations.AlterModelOptions(
            name="userinfo",
            options={
                "verbose_name": "Информация о пользователе",
                "verbose_name_plural": "Информация о пользователях",
            },
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="communication_method",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_info",
                to="users.communicationmethod",
                verbose_name="Методы связи",
            ),
        ),
    ]
