# Generated by Django 5.0.6 on 2024-05-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, unique=True, verbose_name='Русское название')),
                ('name_en', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Английское название')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='about_en',
            field=models.TextField(blank=True, verbose_name='О себе eng'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='about_ru',
            field=models.TextField(default='', verbose_name='О себе ru'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='style',
            field=models.ManyToManyField(related_name='users_info', to='users.style', verbose_name='Стили'),
        ),
    ]
