# Generated by Django 5.1.2 on 2024-10-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_communicationmethod_options_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
