name: 'antokolsky_backend'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U antokolsky -d antokolsky", "--quiet"]
      interval: 10s
      timeout: 50s
      retries: 3
      start_period: 5s
    env_file:
      - ./.env
  
  backend:
    container_name: backend_container
    image: databorodata/antokolsky_backend:latest
    # image: test
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "python manage.py migrate"
    env_file:
      - ./.env
    volumes:
      - static_backend:/backend_static

  
  nginx:
    image: nginx:latest
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_backend:/static_files
    depends_on:
      - backend
      - postgres
  
volumes:
  postgres_data:
  static_backend: