# Generated by Django 5.1.1 on 2024-09-29 18:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тип деятельности",
                "verbose_name_plural": "Типы деятельности",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, message="Имя автора должно быть длинее 1 символа"
                            ),
                            django.core.validators.MaxLengthValidator(
                                200,
                                message="Имя автора должно быть короче 200 символов",
                            ),
                        ],
                        verbose_name="Имя автора",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1,
                                message="Название работы должно быть длинее 1 символа",
                            ),
                            django.core.validators.MaxLengthValidator(
                                100,
                                message="Название работы должно быть короче 100 символов",
                            ),
                        ],
                        verbose_name="Название работы",
                    ),
                ),
                (
                    "dimension_height",
                    models.PositiveSmallIntegerField(
                        max_length=65535,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Высота должна быть больше или равна 1 см."
                            )
                        ],
                        verbose_name="Высота",
                    ),
                ),
                (
                    "dimension_width",
                    models.PositiveSmallIntegerField(
                        max_length=65535,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Ширина должна быть больше или равна 1 см."
                            )
                        ],
                        verbose_name="Ширина",
                    ),
                ),
                (
                    "dimension_depth",
                    models.PositiveSmallIntegerField(
                        max_length=65535,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Глубина должна быть больше или равна 1 см."
                            )
                        ],
                        verbose_name="Глубина",
                    ),
                ),
                (
                    "cost",
                    models.PositiveIntegerField(
                        max_length=100000, verbose_name="Стоимость"
                    ),
                ),
                ("rating", models.IntegerField(default=0, verbose_name="Рейтинг")),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ("-rating", "cost"),
            },
        ),
        migrations.CreateModel(
            name="VolumetricModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "low",
                    models.FileField(
                        upload_to="landing/volumetric_models_low",
                        verbose_name="Файл низкого разрешения",
                    ),
                ),
                (
                    "high",
                    models.FileField(
                        upload_to="landing/volumetric_models_high",
                        verbose_name="Файл высокого разрешения",
                    ),
                ),
            ],
            options={
                "verbose_name": "3D Модель",
                "verbose_name_plural": "3D Модели",
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="landing/project_images", verbose_name="Изображение"
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        height_field="86",
                        null=True,
                        upload_to="",
                        verbose_name="Превью изображения",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_images",
                        to="landing.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение проекта",
                "verbose_name_plural": "Изображения проекта",
                "ordering": ("project", "image"),
            },
        ),
        migrations.CreateModel(
            name="Respondent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                ("country", models.CharField(max_length=50, verbose_name="Страна")),
                (
                    "organization",
                    models.CharField(max_length=50, verbose_name="Организация"),
                ),
                (
                    "organization_website",
                    models.URLField(blank=True, null=True, verbose_name="Сайт"),
                ),
                (
                    "activity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing.activitytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Респондент",
                "verbose_name_plural": "Респонденты",
                "ordering": ("organization",),
            },
        ),
    ]
