# Generated by Django 5.1.1 on 2024-09-30 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cost",
            field=models.PositiveIntegerField(verbose_name="Стоимость"),
        ),
        migrations.AlterField(
            model_name="project",
            name="dimension_depth",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Глубина должна быть больше или равна 1 см."
                    )
                ],
                verbose_name="Глубина",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="dimension_height",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Высота должна быть больше или равна 1 см."
                    )
                ],
                verbose_name="Высота",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="dimension_width",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Ширина должна быть больше или равна 1 см."
                    )
                ],
                verbose_name="Ширина",
            ),
        ),
        migrations.RemoveField(
            model_name="respondent",
            name="activity_type",
        ),
        migrations.AddField(
            model_name="respondent",
            name="activity_type",
            field=models.ManyToManyField(to="landing.activitytype"),
        ),
    ]
