# Generated by Django 5.1.1 on 2024-09-30 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_alter_project_cost_alter_project_dimension_depth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="respondent",
            name="activity_type",
        ),
        migrations.AddField(
            model_name="respondent",
            name="activity_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="landing.activitytype",
            ),
            preserve_default=False,
        ),
    ]
