# Generated by Django 5.1.1 on 2024-09-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0003_remove_respondent_activity_type_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="LandingProject",
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Превью изображения"
            ),
        ),
    ]
