# Generated by Django 5.1.1 on 2024-10-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0004_rename_project_landingproject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                upload_to="landing/project_images/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="landing/project_images/previews/",
                verbose_name="Превью изображения",
            ),
        ),
    ]
