# Generated by Django 5.1.2 on 2024-10-18 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0006_sculptureorder"),
        ("users", "0003_alter_user_managers_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respondent",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respondents",
                to="users.country",
                verbose_name="Страна",
            ),
        ),
    ]
