# Generated by Django 5.0.7 on 2024-07-29 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название Русское"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название Английское"
                    ),
                ),
                (
                    "iso",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        unique=True,
                        verbose_name="ISO классификация страны",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
                "ordering": ("name_ru",),
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, verbose_name="Название Русское"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, verbose_name="Название Английское"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="countries.country",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "ordering": ("name_ru",),
            },
        ),
    ]
