name: uploading to test server
on: [push]
env:
    BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/antokolsky_backend:latest
jobs:
    build_and_push_to_docker_hub:
        name: Push Docker Image to Docker Hub
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/development'
        steps:
            - name: Check out repo
              uses: actions/checkout@v4

            - name: Login to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up docker buildx
              uses: docker/setup-buildx-action@v3

            - name: Push to Docker Hub
              uses: docker/build-push-action@v5
              with:
                push: true
                file: ./Dockerfile
                tags: ${{ env.BACKEND_IMAGE }}
    deploy:
        runs-on: ubuntu-latest
        needs: build_and_push_to_docker_hub
        if: github.ref == 'refs/heads/development'
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            - name: copy docker-compose.yaml
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.HOST_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                passphrase: ${{ secrets.PASSPHRASE }}
                source: "docker-compose.yaml"
                target: "antokolsky"
                debug: true
            - name: copy nginx.conf
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.HOST_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                passphrase: ${{ secrets.PASSPHRASE }}
                source: "nginx.conf"
                target: "antokolsky"
                debug: true
            - name: ssh to remote server
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.HOST_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                passphrase: ${{ secrets.PASSPHRASE }}
                script: |
                  cd ~/antokolsky
                  sudo docker compose stop
                  sudo docker pull ${{env.BACKEND_IMAGE }}
                  sudo docker compose up -d
                  sudo docker image prune -f